---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgB+6gTSpNJRLoldCcuWTQCkOFmw29gckJh5OBP5BICC1p6L7NI4bXIB2jqQ0cRH0UddMJ0YqqizGeKtviNBLII4mKTgUUMTZ/vCa4HioOErynetrYmkrsoAPbuzVsgbz7x7M2AtT8TiL5Z+viY4nyjijVXpHvxY6fKGoBatxISkmO/ozAy8gTtMsU+rspRtPYUbEdgkzHgT3wrEbZE23jfVDE7c/lho5UcS7KxkoPha+dzmZS+GSEKIr09fpuxzLGRpRa/kLCAh9YlQtYfMW9+nVnnJs6lEG+WVNvtkpyEb/4obSmbr1rRsZuF4XYquLcb3Y3oSlqW/LM6w3Xct1Repl4O+UjY88Axf69YnQc8koIdbEXw1qRQlXFqy4XeubFDX90NKx/MvYFknqt2EeoUiD7OERaFdXUUORDjaSyjAd91RRxtiPv9T1JLooSvWC1Vidgurg1FBm5l4Eg6t2dvu0s4q9wgdvJ9+GvuxgtOT1ks6fd2vnnarC7t80Q05ASccgD3tYtPNrRIJQnL3noeljXBFEJCkVAckgrr7BS69WpzkOiJvaVnP+HNq4s0vbiFriobtsBk0lzg1eM4pdbm63dkQdI96KJ79qgF0cw8rR6w/HDRz6nxILFh1mDOZAZSPGh7WFZqEyUKFsOscQFnerlQK8BLURIINcwVZEiky6PH+9uYSyeY05+yooiH8gtks4XbTn7ZZfMNrkAw=
    username: AgBaFfgoXqg50gD9ZpnYE3u9TlEhK/9FTI6tkQswWEpYLdGqHeLsevyCRzh3aWI64dcuZqlXPJgmQIi2XjJ4C80b3sK3VVbLvbUVXJ19pK2j7XtxITadRRmMDx5TzpkTCr9M5cb49oFZ07ogTYiyfMg6cLODoZ7UFoy60YqCOgLeABAOvvjdaJxqcVYp8TuBUkxn6NNEcHfTJ5+uY4WI+eYr8MrSGdWAD4QcO1eJmSHGFClU/0tC1++vUl7r4oIux5XW/5n5af7Knh4Q+OYRafFMqOhlQvU0tLMzPkcgShFv5NlpbIe6J0+p0jChVQD0ekDxkMVLIvlEBdcthOwZYPsMmeVXi6VgW/99Zurw0UGzrZstBXgfKxAdi4a5hb1vGcrzpsE5jQPZDGYVbNpkohHEaCGLzrChd61MSv33II948IJIzWqoAw/VXcvuU7VtCs8wtGO4qVl4GDxClTUaKyGfEW79ViN5kKtQ0EleAhLIOSmLPHSK+wzCG/1LrjLJD5/oERaSp6FDX4vpMpCYtbqipMIPnBidoSQR75RKvq1rSTnsBR6uQYIIzgo9Nt2ho4+r1OxKkhQHFhnVz/x6b3YDDl/8gNRwrjnKrrxmTzy3m4WTri6yd+ryZb20nrNW5sFF0v6VjAec6sR/aHGwJ42eoIH+CuTigJCUw3wWiFtJ1YV5ZQAesMt/YV9+oh0ojVZe7QTFMqPplRg6ww==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
